---
  - name: Delete former backup
    file:
      path=/home/{{user}}/{{app}}_backup
      state=absent

  - name: Stat app directory
    stat: path=/home/{{user}}/{{app}}
    register: folder_stat

  - name: Backup current app if any
    command: mv /home/{{user}}/{{app}} /home/{{user}}/{{app}}_backup
    when: folder_stat.stat.exists

  - name: Make sure directory does not exist
    file:
      path=/home/{{user}}/{{app}}
      state=absent

  - name: Install git
    become: yes
    apt:
      name=git
      state=latest

  - name: Fetch version
    git:
      repo={{repo}}
      depth=1
      version={{version}}
      dest=/home/{{user}}/{{app}}

  - name: Create stdout log file
    file:
      path=/home/{{user}}/{{app}}/out.log
      state=touch

  - name: Create error log file
    file:
      path=/home/{{user}}/{{app}}/error.log
      state=touch
...
