---
  - name: Install package
    become: yes
    apt:
      name=supervisor
      state=latest

  - name: App configuration
    become: yes
    template:
      src=templates/app_config.j2
      dest=/etc/supervisor/conf.d/{{app}}.conf
...
